spring.application.name=prueba-tenpo

server.servlet.context-path=/tenpo
spring.jpa.hibernate.ddl-auto=update

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#Postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://db:5432/tenpo_db
spring.datasource.username=admin
spring.datasource.password=admin123

#Redis
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.password=admin123
spring.data.redis.timeout=60000

#Variables
app.data.variables.shouldFail=false
app.data.variables.fixedPercentage=12.0

debug=false
